---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaultkubeauths.vault.controlplane.io
spec:
  group: vault.controlplane.io
  names:
    kind: VaultKubeAuth
    listKind: VaultKubeAuthList
    plural: vaultkubeauths
    singular: vaultkubeauth
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: VaultKubeAuth is the Schema for the vaultkubeauths API
          properties:
            apiVersion:
              description: |
                'APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info:
                https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: |
                'Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info:
                https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: Spec defines the desired state of VaultKubeAuth
              type: object
              properties:
                cluster_api_addr:
                  type: string
                vault_addr:
                  type: string
                vault_mount_path:
                  type: string
                vault_mount_admin_policy:
                  type: string
                vault_token:
                  type: string
              required:
                - cluster_api_addr
                - vault_addr
                - vault_mount_path
                - vault_mount_admin_policy
                - vault_token
            status:
              description: Status defines the observed state of VaultKubeAuth
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
