---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-trust-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vault-trust-operator
  template:
    metadata:
      labels:
        name: vault-trust-operator
      annotations:
        openshift.io/scc: restricted
    spec:
      serviceAccountName: vault-trust-operator
      containers:
        - name: vault-trust-operator
          # Replace this with the built image name
          image: "REPLACE_IMAGE"
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "vault-trust-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 3
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "0.5"
              memory: 32Mi
            limits:
              cpu: "1"
              memory: 256Mi
      volumes:
        - name: runner
          emptyDir: {}
