apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-trust-operator
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - services/finalizers
      - configmaps
    verbs:
      - create
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - get
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - list
      - get
      - patch
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - vault-trust-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - vault.controlplane.io
    resources:
      - vaultkubeauths
      - vaultkubeauths/status
      - vaultkubeauths/finalizers
      - vaultkuberoles
      - vaultkuberoles/status
      - vaultkuberoles/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
