kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-trust-operator
subjects:
  - kind: ServiceAccount
    name: vault-trust-operator
roleRef:
  kind: Role
  name: vault-trust-operator
  apiGroup: rbac.authorization.k8s.io
