---
apiVersion: v1
kind: Pod
metadata:
  name: vault-client
  labels:
    app.kubernetes.io/instance: vault-client
    app.kubernetes.io/name: vault-client
spec:
  containers:
    - name: vault-client
      image: library/vault:latest
      command:
        - sleep
        - 1h
  serviceAccountName: vault-client
