---
apiVersion: v1
kind: Pod
metadata:
  name: vault
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
spec:
  containers:
    - name: vault
      image: vault:1.4.2
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8200
          name: http
          protocol: TCP
      volumeMounts:
        - name: home
          mountPath: /home/vault
        - name: bootstrap-script
          mountPath: /home/vault/bin
      env:
        - name: VAULT_ADDR
          value: http://127.0.0.1:8200
        - name: SKIP_CHOWN
          value: "true"
        - name: SKIP_SETCAP
          value: "true"
        - name: HOME
          value: /home/vault
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: root
      securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        runAsUser: 1000570000
  securityContext:
    fsGroup: 1000570000
  volumes:
    - name: home
      emptyDir: {}
    - name: bootstrap-script
      configMap:
        name: vault-policy-bootstrap
        defaultMode: 0755
